//import type { Metadata } from "next";
//import { Inter } from "next/font/google";
//import "./globals.css";
//import Navbar from "./components/navbar/Navbar";
//import Sidebar from "./components/sidebar/Sidebar.jsx";
//import { Web3AuthSignerProvider } from "./context/web3-auth-signer";

//const inter = Inter({ subsets: ["latin"] });

//export const metadata: Metadata = {
//  title: "BLOK Capital Community",
//  description: "Generated by create next app",
//};

//export default function RootLayout({
//  children,
//}: {
//  children: React.ReactNode;
//}) {
//  return (
//    <html lang="en">
//      <body className={inter.className}>
//        <Web3AuthSignerProvider>
//          <div className="fixed top-0 w-full z-50">
//            <Navbar />
//          </div>

//          <div className="container mx-auto px-20 pt-32">
//            <div className=" flex lg:space-x-10 space-x-5 w-full ">
//              <div className="fixed w-72 ">
//                <Sidebar />
//              </div>
//              <div className="pl-80 w-full   ">{children}</div>
//            </div>
//          </div>
//        </Web3AuthSignerProvider>
//      </body>
//    </html>
//  );
//}
//responshive

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Sidebar from "./components/sidebar/Sidebar.jsx";
import { Web3AuthSignerProvider } from "./context/web3-auth-signer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BLOK Capital Community",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3AuthSignerProvider>
          <div className="fixed top-0 w-full z-50">
            <Navbar />
          </div>
          <div className="container mx-auto  sm:px-6 md:px-5 pt-16 sm:pt-16 md:pt-24">
            <div className="flex flex-col px-5 sm:flex-row space-y-6 sm:space-y-0 sm:space-x-10 w-full">
              <div className="fixed w-72">
                <Sidebar />
              </div>
              <div className="flex-grow w-full pl-72">{children}</div>
            </div>
          </div>
        </Web3AuthSignerProvider>
      </body>
    </html>
  );
}
